if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()

function(message)
  list(GET ARGV 0 MessageType)
  if(MessageType STREQUAL FATAL_ERROR OR MessageType STREQUAL SEND_ERROR)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${BoldRed}${ARGV}${ColourReset}")
  elseif(MessageType STREQUAL WARNING)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${BoldYellow}${ARGV}${ColourReset}")
  elseif(MessageType STREQUAL AUTHOR_WARNING)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${BoldCyan}${ARGV}${ColourReset}")
  elseif(MessageType STREQUAL STATUS)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${Green}${ARGV}${ColourReset}")
  else()
    _message("${ARGV}")
  endif()
endfunction(message)

function(includecfiles)
file(GLOB_RECURSE SRC_FILES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c)
endfunction()

function(includegeneratedfiles)
file(GLOB_RECURSE SRC_FILES ${CMAKE_CURRENT_SOURCE_DIR}/generated/*)
endfunction()

function(commonsrc ARG1 ARG2)
  file(GLOB_RECURSE SRC_FILES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp)
  if (${ARG1} STREQUAL ".c")
    includecfiles()
  endif
  if (${ARG2} STREQUAL "GENERATED")
    includegeneratedfiles()
  endif
  SET(${TARGET_NAME} ${CURRENT_APP} PARENT_SCOPE)
endfunction(commonsrc)

function(MODULE ARG1 ARG2 ARG3)
  commonsrc(${ARG2} ${ARG3})
  include(${CMAKE_BINARY_DIR}/../.cmakefiles/CMakeModule.cmake)
  if (TYPE STREQUAL "shared")
    SET(MODULE_OUTPUT_MODE "SHARED")
  elseif(TYPE STREQUAL "static")
    SET(MODULE_OUTPUT_MODE "STATIC")
  endif()
endfunction()

function(APP TARGET_NAME ARG1 ARG2)
commonsrc(${ARG2} ${ARG3})
  if (${ARG1} STREQUAL ".c")
    includecfiles()
  endif()
  include(${CMAKE_BINARY_DIR}/../.cmakefiles/CMakeApp.cmake)
endfunction()

function(TEST TARGET_NAME)
commonsrc(${ARG2} ${ARG3})
include(${CMAKE_BINARY_DIR}/../.cmakefiles/CMakeTest.cmake)
endfunction()